package com.codedisaster.steamworks;

import java.nio.Buffer;

/**
 * <ul>
 * <li>{@link SteamApps}</li>
 * <li>{@link SteamController}</li>
 * <li>{@link SteamEncryptedAppTicket}</li>
 * <li>{@link SteamFriends}</li>
 * <li>{@link SteamGameServer}</li>
 * <li>{@link SteamGameServerStats}</li>
 * <li>{@link SteamHTTP} &#8594; {@link SteamGameServerHTTP}</li>
 * <li>{@link SteamMatchmaking}</li>
 * <li>{@link SteamMatchmakingPingResponse}</li>
 * <li>{@link SteamMatchmakingPlayerResponse}</li>
 * <li>{@link SteamMatchmakingRulesResponse}</li>
 * <li>{@link SteamMatchmakingServerListResponse}</li>
 * <li>{@link SteamMatchmakingServers}</li>
 * <li>{@link SteamNetworking} &#8594; {@link SteamGameServerNetworking}</li>
 * <li>{@link SteamRemoteStorage}</li>
 * <li>{@link SteamScreenshots}</li>
 * <li>{@link SteamUGC}</li>
 * <li>{@link SteamUser}</li>
 * <li>{@link SteamUserStats}</li>
 * <li>{@link SteamUtils}</li>
 * </ul>
 */
abstract class SteamInterfaceImpl implements SteamInterface {

	protected long callback;

	SteamInterfaceImpl() {
		this(0L);
	}

	SteamInterfaceImpl(long callback) {
		this.callback = callback;
	}

	void setCallback(long callback) {
		this.callback = callback;
	}

	@Override
	public void dispose() {
		deleteCallback(callback);
	}

	static void checkBuffer(Buffer buffer) throws SteamException {
		if (!buffer.isDirect()) {
			throw new SteamException("Direct buffer required.");
		}
	}

	static void checkArray(byte[] array, int length) throws SteamException {
		if (array.length < length) {
			throw new SteamException("Array too small, " + array.length + " found but " + length + " expected.");
		}
	}

	/*
	 * The native API allows passing NULL char pointers in some places, but the
	 * wrapper code generated by jnigen doesn't check for null Strings. So we
	 * silently convert to an empty string here, and check again before calling the
	 * native function.
	 */
	static String maybeNull(String argument) {
		return (argument != null) ? argument : "";
	}

	/*
	 * JNI #include "SteamCallbackAdapter.h"
	 */

	protected static native void deleteCallback(long callback);
	/*
	 * delete (SteamCallbackAdapter*) callback;
	 */

}
