/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_codedisaster_steamworks_SteamRemoteStorage */

#ifndef _Included_com_codedisaster_steamworks_SteamRemoteStorage
#define _Included_com_codedisaster_steamworks_SteamRemoteStorage
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_codedisaster_steamworks_SteamRemoteStorage
 * Method:    fileWrite
 * Signature: (JLjava/lang/String;Ljava/nio/ByteBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_codedisaster_steamworks_SteamRemoteStorage_fileWrite
  (JNIEnv *, jclass, jlong, jstring, jobject, jint);

/*
 * Class:     com_codedisaster_steamworks_SteamRemoteStorage
 * Method:    fileRead
 * Signature: (JLjava/lang/String;Ljava/nio/ByteBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_codedisaster_steamworks_SteamRemoteStorage_fileRead
  (JNIEnv *, jclass, jlong, jstring, jobject, jint);

/*
 * Class:     com_codedisaster_steamworks_SteamRemoteStorage
 * Method:    fileDelete
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_codedisaster_steamworks_SteamRemoteStorage_fileDelete
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_codedisaster_steamworks_SteamRemoteStorage
 * Method:    fileExists
 * Signature: (JLjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_codedisaster_steamworks_SteamRemoteStorage_fileExists
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_codedisaster_steamworks_SteamRemoteStorage
 * Method:    getFileSize
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_codedisaster_steamworks_SteamRemoteStorage_getFileSize
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_codedisaster_steamworks_SteamRemoteStorage
 * Method:    getFileCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_codedisaster_steamworks_SteamRemoteStorage_getFileCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_codedisaster_steamworks_SteamRemoteStorage
 * Method:    getFileNameAndSize
 * Signature: (JI[I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_codedisaster_steamworks_SteamRemoteStorage_getFileNameAndSize
  (JNIEnv *, jclass, jlong, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
